-- Migration 015: Add pre_mortem column to report_version
-- Stores adversarial-persona objections (CFO/CISO/Procurement) per report version.
-- Lifecycle is bound to one report_version row: regenerating the report creates
-- a new row with pre_mortem=NULL, which is the cache-invalidation signal.

ALTER TABLE report_version
    ADD COLUMN IF NOT EXISTS pre_mortem JSON NULL;

COMMENT ON COLUMN report_version.pre_mortem IS
    'Adversarial-persona objections + counter-responses generated by the Pre-Mortem feature. '
    'NULL = not yet generated for this version. Regenerated on demand via POST /api/v1/pre-mortem/{chat_history_id}.';
