"""baseline — current schema as of the 21 hand-written SQL migrations (001..021)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-01

This is the Alembic baseline for an existing project. It reproduces the *current*
schema directly from the live SQLAlchemy metadata in `src/models.py` (which already
reflects the net effect of migrations/001..021_*.sql).

Usage:
- Existing DBs that already ran the 21 SQL files (e.g. staging):
      alembic stamp 0001_baseline      # mark as applied WITHOUT running upgrade()
- Fresh DBs (e.g. a brand-new production RDS):
      alembic upgrade head             # runs upgrade() to build the whole schema

`create_all(checkfirst=True)` is idempotent, so re-running is safe. From here on,
schema changes are normal autogenerated revisions stacked on top of this baseline.

Caveat: any *raw-SQL-only* artifacts that were never declared on the ORM models
(e.g. a hand-rolled composite index) are not reproduced by create_all. Add such
items as explicit follow-up revisions if a fresh DB needs them for performance.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

import models

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Build every table defined on the app's models. checkfirst=True makes this a
    # no-op for tables that already exist (so it's safe even if partially applied).
    bind = op.get_bind()
    models.Base.metadata.create_all(bind=bind, checkfirst=True)


def downgrade() -> None:
    bind = op.get_bind()
    models.Base.metadata.drop_all(bind=bind)
